[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['cd .. && pnpm install --filter=@music-monitor/frontend...']

[phases.build]
cmds = ['cd .. && pnpm --filter=@music-monitor/frontend build']

[start]
cmd = 'pnpm start'
