[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['cd .. && pnpm install --filter=@music-monitor/backend...']

[phases.build]
cmds = ['cd .. && pnpm --filter=@music-monitor/backend build']

[start]
cmd = 'pnpm start:prod'
